# Generated by Django 5.2.7 on 2025-11-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineage', '0008_agent_order_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('IN_DEEP_COVER', 'In-Deep-Cover'), ('COMPROMISED', 'Compromised'), ('INACTIVE', 'Inactive'), ('MIA', 'Missing in Action'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20),
        ),
    ]
