# Generated by Django 5.2.7 on 2025-11-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineage', '0009_alter_agent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='dev_plan_focus',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='agent',
            name='dev_plan_next',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='agent',
            name='dev_plan_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='duress_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='agent',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='secure_comms_channel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agent',
            name='secure_comms_contact_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
