# Generated by Django 5.2.7 on 2025-11-02 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_indexprofile_affiliations'),
        ('lineage', '0010_agent_dev_plan_focus_agent_dev_plan_next_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='index_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineage_agent', to='index.indexprofile'),
        ),
    ]
