# Generated by Django 5.2.7 on 2025-10-30 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_indexprofile_picture_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=100, null=True)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_links', to='scales.faction')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_links', to='index.indexprofile')),
            ],
            options={
                'unique_together': {('profile', 'faction')},
            },
        ),
    ]
