# Generated by Django 5.2.7 on 2025-10-31 11:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_indexaffiliation_alter_indexprofile_affiliations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupaIndexProfile',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('classification', models.TextField()),
                ('affiliation_id', models.UUIDField(blank=True, null=True)),
                ('status', models.TextField()),
                ('threat_level', models.TextField()),
                ('biography', models.TextField(blank=True, null=True)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('weaknesses', models.TextField(blank=True, null=True)),
                ('known_locations', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('known_vehicles', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('surveillance_files', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'index_profiles',
                'managed': False,
            },
        ),
    ]
