# Generated by Django 5.2.7 on 2025-10-31 13:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_profileconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileFaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_id', models.UUIDField()),
                ('faction_id', models.UUIDField()),
                ('relationship', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profile_factions',
                'managed': False,
            },
        ),
    ]
