# Generated by Django 5.2.7 on 2025-11-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_profilefaction'),
    ]

    operations = [
    ]
