# Generated by Django 5.2.7 on 2025-11-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_indexprofile_affiliations'),
        ('scales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexprofile',
            name='affiliations',
            field=models.ManyToManyField(blank=True, related_name='index_profiles', through='index.IndexAffiliation', to='scales.faction'),
        ),
    ]
