# Generated by Django 5.2.7 on 2025-11-02 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_indexprofile_affiliations'),
        ('scales', '0006_remove_obsolete_faction_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(blank=True, help_text='e.g., Family, Rival, Known Associate', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ProfileConnection',
        ),
        migrations.DeleteModel(
            name='ProfileFaction',
        ),
        migrations.DeleteModel(
            name='SupaIndexProfile',
        ),
        migrations.AlterUniqueTogether(
            name='indexaffiliation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='indexprofile',
            name='affiliations',
        ),
        migrations.AddField(
            model_name='indexprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='indexaffiliation',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scales.faction'),
        ),
        migrations.AlterField(
            model_name='indexaffiliation',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.indexprofile'),
        ),
        migrations.AlterField(
            model_name='indexprofile',
            name='aliases',
            field=models.TextField(blank=True, help_text='Comma-separated list of aliases.'),
        ),
        migrations.AlterField(
            model_name='indexprofile',
            name='classification',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='indexprofile',
            name='known_locations',
            field=models.TextField(blank=True, help_text='Comma-separated list.'),
        ),
        migrations.AlterField(
            model_name='indexprofile',
            name='known_vehicles',
            field=models.TextField(blank=True, help_text='Comma-separated list.'),
        ),
        migrations.AlterField(
            model_name='indexprofile',
            name='status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='indexprofile',
            name='strengths',
            field=models.TextField(blank=True, help_text='Comma-separated list.'),
        ),
        migrations.AlterField(
            model_name='indexprofile',
            name='surveillance_urls',
            field=models.TextField(blank=True, help_text='Comma-separated list of URLs.'),
        ),
        migrations.AlterField(
            model_name='indexprofile',
            name='threat_level',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='indexprofile',
            name='weaknesses',
            field=models.TextField(blank=True, help_text='Comma-separated list.'),
        ),
        migrations.AddField(
            model_name='indexconnection',
            name='from_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='index.indexprofile'),
        ),
        migrations.AddField(
            model_name='indexconnection',
            name='to_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='index.indexprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='indexconnection',
            unique_together={('from_profile', 'to_profile')},
        ),
    ]
