# Generated by Django 5.2.7 on 2025-11-01 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0007_indexprofile_affiliations'),
        ('lineage', '0008_agent_order_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="The agent's real name, if known.", max_length=255)),
                ('alias', models.CharField(blank=True, max_length=100, unique=True)),
                ('rank', models.CharField(blank=True, max_length=100)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('known_locations', models.TextField(blank=True)),
                ('known_vehicles', models.TextField(blank=True)),
                ('picture_url', models.URLField(blank=True, max_length=500, null=True)),
                ('surveillance_images', models.TextField(blank=True, help_text='Comma-separated URLs of surveillance images.')),
                ('threat_level', models.PositiveIntegerField(blank=True, default=50, help_text='A score from 0-100 indicating threat level.', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('threat_index', models.PositiveIntegerField(default=50, help_text='A score from 0-100')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('picture_url', models.URLField(blank=True, max_length=500, null=True)),
                ('supa_uuid', models.UUIDField(blank=True, help_text='Supabase factions UUID (for Index linkage)', null=True)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('allies', models.TextField(blank=True, default='')),
                ('rivals', models.TextField(blank=True, default='')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('threat_index', models.IntegerField(blank=True, null=True)),
                ('member_count', models.IntegerField(blank=True, null=True)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='scales.faction')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FactionMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.CharField(choices=[('Leader', 'Leader'), ('Lieutenant', 'Lieutenant'), ('Enforcer', 'Enforcer'), ('Associate', 'Associate'), ('Supporter', 'Supporter'), ('Informant', 'Informant'), ('Unknown', 'Unknown')], default='Associate', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='scales.faction')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faction_memberships', to='index.indexprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('faction', 'profile')},
            },
        ),
        migrations.AddField(
            model_name='faction',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='faction_affiliations', through='scales.FactionMembership', to='index.indexprofile'),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('INFORMANT', 'Informant'), ('LEVERAGE', 'Leverage (Blackmail)'), ('FAMILY_TIE', 'Family Tie'), ('PAST_AFFILIATION', 'Past Affiliation'), ('RIVAL', 'Rival'), ('HANDLER', 'Handler')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lineage_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_connections', to='lineage.agent')),
                ('scales_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='scales.agent')),
            ],
            options={
                'unique_together': {('scales_agent', 'lineage_agent')},
            },
        ),
        migrations.CreateModel(
            name='FactionDiplomacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(blank=True, help_text="Name of the target if it's not in the system.", max_length=150)),
                ('relation', models.CharField(choices=[('ALLY', 'Ally'), ('RIVAL', 'Rival'), ('NEUTRAL', 'Neutral')], default='NEUTRAL', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomacy_outgoing', to='scales.faction')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diplomacy_incoming', to='scales.faction')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('source', 'target', 'relation')},
            },
        ),
    ]
