# Generated by Django 5.2.7 on 2025-11-01 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factionmembership',
            options={'ordering': []},
        ),
    ]
