# Generated by Django 5.2.7 on 2025-11-01 21:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0002_alter_factionmembership_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factionmembership',
            options={'ordering': ['-added_at']},
        ),
        migrations.AlterField(
            model_name='factionmembership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
    ]
