# Generated by Django 5.2.7 on 2025-11-01 21:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0003_alter_factionmembership_options_and_more'),
    ]

    operations = [
    ]
