# Generated by Django 5.2.7 on 2025-11-01 21:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0004_remove_factionmembership_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factionmembership',
            name='created_at',
        ),
        migrations.AddField(
            model_name='factionmembership',
            name='added_at',
            field=models.DateTimeField(db_column='added_at', default=django.utils.timezone.now),
        ),
    ]
