# Generated by Django 4.2.13 on 2025-11-02 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0005_remove_factionmembership_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faction',
            name='allies',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='rivals',
        ),
    ]