# Generated by Django 5.2.7 on 2025-11-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0006_remove_obsolete_faction_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='allies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='faction',
            name='rivals',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='faction',
            name='surveillance_urls',
            field=models.TextField(blank=True, help_text='Comma-separated list of surveillance file URLs.'),
        ),
    ]
