# Generated by Django 5.2.7 on 2025-11-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0007_faction_allies_faction_rivals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faction',
            name='threat_index',
        ),
        migrations.RemoveField(
            model_name='factionhistory',
            name='threat_index',
        ),
        migrations.AddField(
            model_name='faction',
            name='threat_level',
            field=models.CharField(choices=[('DORMANT', 'Dormant'), ('NOMINAL', 'Nominal'), ('ELEVATED', 'Elevated'), ('SEVERE', 'Severe'), ('CRITICAL', 'Critical')], default='DORMANT', max_length=20),
        ),
        migrations.AddField(
            model_name='factionhistory',
            name='threat_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
