# Generated by Django 5.2.7 on 2025-11-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0008_remove_faction_threat_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factionmembership',
            name='affiliation',
            field=models.CharField(choices=[('Leader', 'Leader'), ('High ranking member', 'High ranking member'), ('Member', 'Member'), ('Associate', 'Associate'), ('Hangaround', 'Hangaround'), ('Affiliate', 'Affiliate'), ('Supporter', 'Supporter'), ('Informant', 'Informant'), ('Unknown', 'Unknown')], default='Associate', max_length=32),
        ),
    ]
