# Generated by Django 5.2.7 on 2025-11-02 16:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codex', '0015_alter_notification_notif_type'),
        ('lineage', '0011_agent_index_profile'),
        ('index', '0009_indexconnection_delete_profileconnection_and_more'),
        ('scales', '0009_alter_factionmembership_affiliation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ALLOCATED', 'Allocated'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('objective', models.TextField()),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active'), ('CONCLUDED - SUCCESS', 'Concluded - Success'), ('CONCLUDED - FAILURE', 'Concluded - Failure'), ('COMPROMISED', 'Compromised')], default='PLANNING', max_length=50)),
                ('assets', models.TextField(blank=True, help_text='Placeholder for assets from The Vault.')),
                ('success_probability', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('collateral_risk', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('after_action_report', models.TextField(blank=True)),
                ('contingencies', models.ManyToManyField(blank=True, related_name='operations', to='codex.codexentry')),
                ('individual_targets', models.ManyToManyField(blank=True, related_name='targeted_operations', to='index.indexprofile')),
                ('targets', models.ManyToManyField(blank=True, related_name='targeted_operations', to='scales.faction')),
            ],
        ),
        migrations.CreateModel(
            name='OperationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_op', models.CharField(blank=True, default='Field Agent', max_length=100)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineage.agent')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loom.operation')),
            ],
            options={
                'unique_together': {('operation', 'agent')},
            },
        ),
        migrations.AddField(
            model_name='operation',
            name='personnel',
            field=models.ManyToManyField(blank=True, related_name='operations', through='loom.OperationAssignment', to='lineage.agent'),
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='loom.operation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AssetRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_approvals', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='loom.asset')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_requests', to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='loom.operation')),
            ],
            options={
                'unique_together': {('operation', 'asset')},
            },
        ),
    ]
