# Generated by Django 5.2.7 on 2025-11-02 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_indexconnection_delete_profileconnection_and_more'),
        ('loom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assetrequisition',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='operation',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='contingencies',
        ),
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='individual_targets',
            field=models.ManyToManyField(blank=True, related_name='targeted_in_operations', to='index.indexprofile'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ALLOCATED', 'Allocated'), ('MAINTENANCE', 'Maintenance'), ('COMPROMISED', 'Compromised'), ('DESTROYED', 'Destroyed')], default='AVAILABLE', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('VEHICLE', 'Vehicle'), ('PROPERTY', 'Property'), ('FINANCIAL', 'Financial Instrument'), ('EQUIPMENT', 'Equipment'), ('INTEL', 'Intel Packet')], max_length=50),
        ),
        migrations.AlterField(
            model_name='assetrequisition',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requisitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assetrequisition',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
