# Generated by Django 5.2.7 on 2025-11-03 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loom', '0002_alter_assetrequisition_unique_together_and_more'),
        ('codex', '0015_alter_notification_notif_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationReportLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('linked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_links', to='loom.operation')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_links', to='codex.echo')),
            ],
            options={
                'unique_together': {('operation', 'report')},
            },
        ),
    ]
